Do not set GOOS/GOARCH
kiegroup/kogito-operator pull request #1067
Opened 2021-11-09 14:24 UTC by yselkowitz

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
﻿golang automatically compiles natively, and explicitly setting these
prevents multi-architecture builds from working.
</summary>

* <b>Run operator BDD testing</b>
  Please add comment: <b>/jenkins test</b>

* <b>Run RHPAM operator BDD testing</b>
  Please add comment: <b>/jenkins RHPAM test</b>
</details>

2021-11-09 17:44 UTC, spolti commented
/jenkins test

2021-11-09 19:09 UTC, spolti commented
/jenkins retest this

2021-11-09 19:47 UTC, spolti requested changes

2021-11-09 19:47 UTC, spolti commented on modules/org.kie.kogito.app.builder/install.sh
> +CGO_ENABLED=0 GO111MODULE=on go build -a -o manager main.go
probably it needs to be adjusted on the other places as well:

- the kogito-cli will not be part of it, but might be good to remove it from there as well (go-build-cli and go-install-cli scripts)
- modules/org.kie.kogito.app.buildProfilingOperator/install.sh
- modules/org.kie.kogito.rhpam.builder/install.sh
-

2021-11-12 19:30 UTC, spolti approved these changes

2021-11-15 05:06 UTC, vaibhavjainwiz approved these changes

2021-11-15 08:08 UTC, sutaakar approved these changes

2021-11-15 08:08 UTC, sutaakar commented
/jenkins test

2021-11-15 10:50 UTC, radtriste approved these changes

2021-11-16 16:36 UTC, spolti commented
/jenkins retest this

2021-11-16 17:21 UTC, spolti commented
/jenkins retest this

2021-11-17 15:52 UTC, spolti commented
/jenkins retest this

2021-11-17 15:53 UTC, spolti commented
@radtriste @msmagnanijr is the ci down?

2021-11-17 15:54 UTC, radtriste commented
/jenkins test

2021-11-17 15:56 UTC, msmagnanijr commented
> @radtriste @msmagnanijr is the ci down?
seems to be a timeout in the Openshift control plane. 
I'm going to check the ocp nodes.

2021-11-17 15:58 UTC, spolti commented
> /jenkins test

seems that jenkins does not likes me haha

retest command is not working anymore?

2021-11-17 16:17 UTC, msmagnanijr commented
/jenkins retest this

2021-11-17 16:18 UTC, msmagnanijr commented
> > /jenkins test
> 
> seems that jenkins does not likes me haha
> 
> retest command is not working anymore?

now is working :D   **./[j|J]enkins (re)test**

2021-11-17 17:53 UTC, spolti commented
/jenkins test

2021-11-17 17:54 UTC, spolti commented
/jenkins retest this

2021-11-17 17:59 UTC, spolti commented
/jenkins test

2021-11-17 18:08 UTC, ricardozanini approved these changes

2021-11-18 12:36 UTC, spolti commented
/jenkins test

2021-11-19 13:48 UTC, radtriste commented
Btw, is that change planned to be included in RHPAM 7.12 or 7.13 ?

2021-11-22 17:36 UTC, spolti commented
for now, 7.13;

2021-11-23 20:19 UTC, msmagnanijr commented
/jenkins test

2021-11-23 21:42 UTC, merged

2021-12-07 15:38 UTC, mareknovotny commented
i think we need a backport to kiegroup/rhpam-kogito-operator too