[RHPAM-4129] - Kogito Operator scorecard errors
kiegroup/kogito-operator pull request #1155
Opened 2022-03-14 08:54 UTC by vaibhavjainwiz

Many thanks for submitting your Pull Request :heart:! 

Jira Issue : https://issues.redhat.com/browse/RHPAM-4129

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run operator BDD testing</b>
  Please add comment: <b>/jenkins test</b>

* <b>Run RHPAM operator BDD testing</b>
  Please add comment: <b>/jenkins RHPAM test</b>
</details>

2022-03-14 08:56 UTC, vaibhavjainwiz commented
/jenkins test

2022-03-14 09:37 UTC, sutaakar approved these changes
Looks ok, briefly checked

2022-03-14 09:37 UTC, sutaakar commented
/jenkins test

2022-03-14 10:03 UTC, radtriste commented
@vaibhavjainwiz why such a big change to solve the scorecard errors ?

2022-03-14 11:14 UTC, spolti commented
@radtriste mostly because the way the operator-sdk works, we had to ducplicate the missing classes to the rhpam/v1 api and update how ithose dependencies are called internally, instead referencing v1beta1 api on most places itis now calling a interface that handles better if the call is being done by the rhpam or kogito api.

2022-03-14 14:39 UTC, vaibhavjainwiz commented
/jenkins test

2022-03-14 18:04 UTC, spolti commented on core/kogitoinfra/infinispan_reconciler.go
> +	//For Spring: https://github.com/infinispan/infinispan-spring-boot/blob/master/infinispan-spring-boot-starter-remote/src/test/resources/test-application.properties
shouldbe main.

2022-03-14 18:05 UTC, spolti requested changes
just a minor thing

2022-03-15 05:55 UTC, vaibhavjainwiz commented on core/kogitoinfra/infinispan_reconciler.go
> +	//For Spring: https://github.com/infinispan/infinispan-spring-boot/blob/master/infinispan-spring-boot-starter-remote/src/test/resources/test-application.properties
done

2022-03-15 05:57 UTC, vaibhavjainwiz commented
/jenkins test

2022-03-15 06:03 UTC, vaibhavjainwiz commented
/jenkins test

2022-03-15 19:13 UTC, spolti approved these changes

2022-03-16 10:54 UTC, radtriste approved these changes

2022-03-16 10:54 UTC, radtriste commented
/jenkins RHPAM test

2022-03-16 14:51 UTC, spolti commented
/jenkins RHPAM test

2022-03-16 15:50 UTC, spolti commented
/jenkins RHPAM test

2022-03-16 16:54 UTC, merged