[KIECLOUD-654] - prepare RHPAM and RHPAM Kogito operators for 7.13.1 …
kiegroup/kogito-operator pull request #1274
Opened 2022-09-05 17:56 UTC by spolti

…release

Signed-off-by: spolti <fspolti@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run operator BDD testing</b>
  Please add comment: <b>/jenkins test</b>

* <b>Run RHPAM operator BDD testing</b>
  Please add comment: <b>/jenkins RHPAM test</b>
</details>

2022-09-05 17:57 UTC, spolti commented
/jenkins test rhpam

2022-09-05 19:31 UTC, ricardozanini approved these changes

2022-09-06 05:16 UTC, radtriste requested changes
Please revert go.mod and go.sym changes... This makes the build cli failing ...

2022-09-06 06:30 UTC, radtriste commented
> Please revert go.mod and go.sym changes... This makes the build cli failing ...

Nevermind. I cannot reproduce locally ...

2022-09-06 06:43 UTC, radtriste commented
/jenkins test

2022-09-06 14:00 UTC, spolti commented
/jenkins test

2022-09-07 08:35 UTC, radtriste commented
/jenkins test

2022-09-07 09:12 UTC, radtriste commented
@spolti looks like the `-mod=mod` build option is the one working each time ...

2022-09-07 09:46 UTC, radtriste commented
/jenkins test

2022-09-07 11:10 UTC, radtriste commented on .ci/jenkins/Jenkinsfile
> +    '''
I think that this could be rollbacked

2022-09-08 15:14 UTC, spolti commented
/jenkins test

2022-09-09 08:46 UTC, radtriste commented
/jenkins test

2022-09-12 13:27 UTC, merged