[KOGITO-3653] - RHPAM Kogito operator creates wrong default image tags
kiegroup/kogito-operator pull request #867
Opened 2021-05-10 07:34 UTC by vaibhavjainwiz

Many thanks for submitting your Pull Request :heart:! 

Jira issue : https://issues.redhat.com/browse/KOGITO-5104

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

2021-05-10 09:27 UTC, radtriste requested changes
code looks good. one small change

2021-05-10 09:27 UTC, radtriste commented on core/infrastructure/image.go
>  // GetKogitoImageVersion gets the Kogito Runtime latest micro version based on the Operator current version
```suggestion
// GetKogitoImageVersion gets the Kogito Runtime latest micro version based on the given version
```

2021-05-10 09:27 UTC, radtriste commented
/jenkins test

2021-05-10 09:28 UTC, radtriste commented
for the OLM test I guess the `replaces` should be set to `1.6.0` ?
or we would need to create a new channel ?

2021-05-10 12:36 UTC, sutaakar approved these changes

2021-05-10 12:41 UTC, sutaakar commented
@vaibhavjainwiz Please open PR for master branch first, once merged there it can be backported.
Also please reference branch name in PR subject (if it is not master), otherwise it is easy to overlook that the PR doesn't target master.

2021-05-14 13:26 UTC, ricardozanini commented
Haven't we closed a cherry-pick to 1.6.x? Why open one for 1.5.x? It seems that OLM is failing after this change.

2021-05-17 07:28 UTC, radtriste commented
OLM is not related to the PR but a more global problem in the scripts.... @msmagnanijr is looking into it AFAIK
cherry-pick to 1.6.x was not useful because we won't release from this branch anymore. 1.5.x is still used for the product, so we need the change there ;)

2021-05-17 08:05 UTC, radtriste approved these changes

2021-05-17 12:45 UTC, vaibhavjainwiz commented
/jenkins test

2021-05-17 14:00 UTC, sutaakar commented
/jenkins test

2021-05-17 14:17 UTC, ricardozanini approved these changes

2021-05-17 17:16 UTC, merged